### ISSUE TITLE
iedit is consistently inconsistent in clojure-mode

### ISSUE THREAD

**Issue by WhittlesJr** [syl20bnr/evil-iedit-state#26] opened 2018-12-21 18:17 UTC
At least in clojure-mode, virtually every other time I enter iedit state, and I start editing, only the occurrence I'm on will be edited. The rest of the occurrences in the file stay the same, despite being highlighted. 

If I ESC out and try again, it usually works. 

Does this sound like a clojure-mode problem? If so, please close this and I'll move the issue over to clojure-mode. I may have experienced it on other modes as well, but I can't remember. Plain text mode works perfectly.

**Comment by syl20bnr** [comment] 2020-08-20 13:04
I cannot reproduce the issue. Closing it for now, feel free to reopen if still present for you.

**Closed as completed by syl20bnr** 2020-08-20 13:04 UTC
